services:
  web:
    container_name: middle-test-react
    image: node:20.10.0
    working_dir: /app/web

    volumes:
      - './web:/app/web'
    ports:
      - '3000:3000'
      - '4000:4000'
    command: ["npm", "run", "start"]